# Generated by Django 2.2.5 on 2020-02-11 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_Category', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('slug', models.SlugField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adcategory', to='marketplace.Category')),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('ad_title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField()),
                ('ads_validity', models.DateField()),
                ('price', models.CharField(max_length=30)),
                ('image1', models.TextField(blank=True)),
                ('image2', models.TextField(blank=True)),
                ('image3', models.TextField(blank=True)),
                ('image4', models.TextField(blank=True)),
                ('image5', models.TextField(blank=True)),
                ('image6', models.TextField(blank=True)),
                ('image7', models.TextField(blank=True)),
                ('image8', models.TextField(blank=True)),
                ('image9', models.TextField(blank=True)),
                ('image10', models.TextField(blank=True)),
                ('negotiable', models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No')], max_length=10)),
                ('condition', models.CharField(blank=True, choices=[('bn', 'Brand New'), ('ln', 'Like New(Used Few Times)'), ('e', 'Excellent'), ('g', 'Good'), ('nw', 'Not Working')], max_length=30)),
                ('used_for', models.CharField(blank=True, max_length=100)),
                ('home_delivery', models.CharField(blank=True, choices=[('a', 'Available'), ('na', 'Not Available')], max_length=30)),
                ('delivery_areas', models.CharField(blank=True, choices=[('wa', 'Within my area'), ('wc', 'Within my city'), ('np', 'All over Nepal')], max_length=100)),
                ('delivery_charges', models.CharField(blank=True, max_length=30)),
                ('warranty_type', models.CharField(blank=True, choices=[('s', 'Seller/Shop'), ('m', 'Manufacturer/Importer'), ('n', 'No Warranty')], max_length=30)),
                ('warranty_period', models.CharField(blank=True, max_length=100)),
                ('warranty_includes', models.CharField(blank=True, max_length=300)),
                ('featured', models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No')], default='n', max_length=30)),
                ('ad_status', models.CharField(blank=True, choices=[('a', 'Available'), ('s', 'Sold Out')], default='a', max_length=30)),
                ('views', models.BigIntegerField(default=0)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addsubcategory', to='marketplace.SubCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aduser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
