# Generated by Django 3.0.4 on 2020-03-29 14:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='location',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
        ),
    ]
