# Generated by Django 3.0.4 on 2020-03-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_advertisement_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='ad_status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Sold Out', 'Sold Out')], default='a', max_length=30),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='condition',
            field=models.CharField(blank=True, choices=[('Brand New', 'Brand New'), ('Like New(Used Few Times)', 'Like New(Used Few Times)'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Not Working', 'Not Working')], max_length=30),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='delivery_areas',
            field=models.CharField(blank=True, choices=[('Within My Area', 'Within my area'), ('Within My City', 'Within my city'), ('All over Nepal', 'All over Nepal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='featured',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='n', max_length=30),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='home_delivery',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=30),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='negotiable',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='warranty_type',
            field=models.CharField(blank=True, choices=[('Seller/Shop', 'Seller/Shop'), ('Manufacuturer/Importer', 'Manufacturer/Importer'), ('No Warranty', 'No Warranty')], max_length=30),
        ),
    ]
