# Generated by Django 3.0.4 on 2020-03-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20200329_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='ad_status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Sold Out', 'Sold Out')], default='Available', max_length=30),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='featured',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='warranty_type',
            field=models.CharField(blank=True, choices=[('Seller/Shop', 'Seller/Shop'), ('Manufacturer/Importer', 'Manufacturer/Importer'), ('No Warranty', 'No Warranty')], max_length=30),
        ),
    ]
