# Generated by Django 3.0.4 on 2020-03-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200325_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.TextField(blank=True),
        ),
    ]
